[profile.default]
# Default settings
test-threads = "num-cpus"

[profile.ci]
# CI-specific settings
fail-fast = false
retries = 2
test-threads = "num-cpus"
status-level = "all"
final-status-level = "all" 

# JUnit configuration for test results
[profile.ci.junit]
path = "junit.xml"
report-name = "favkit-tests"
store-success-output = true