name: Rust

on:
  push:
    branches: [ "main" ]
    paths:
      - '**.rs'
      - 'Cargo.toml'
      - 'Cargo.lock'
  pull_request:
    branches: [ "main" ]
    paths:
      - '**.rs'
      - 'Cargo.toml'
      - 'Cargo.lock'

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Lint & Test
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Setup Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Run Lints
        run: |
          nix develop --command make lint

      - name: Run Tests With Coverage
        id: coverage
        run: |
          nix develop --command make coverage-lcov
          nix develop --command make test-junit

      - name: Upload coverage to Codecov
        if: steps.coverage.outcome == 'success'
        uses: codecov/codecov-action@v5
        with:
          files: target/coverage/lcov.info
          name: favkit-coverage
          fail_ci_if_error: true
          verbose: true
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: target/nextest/ci/junit.xml