name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Lint & Test
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Setup Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Run Tests and Lints
        run: |
          # Enter nix shell and run our make targets
          nix develop --command make lint
          nix develop --command make test

      - name: Run Coverage
        run: |
          nix develop --command make coverage-lcov

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: target/coverage/lcov.info
          name: favkit-coverage
          fail_ci_if_error: true
          verbose: true
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}